#!/usr/bin/env python

import os
import shutil
import sys

def pop_last ():
	manifest_filename = ".untar-nc_manifest"
	# Read manifest and revert the changes
	revert_backup(manifest_filename)

def revert_backup (target, backup=None):
	path, basename = os.path.split(target)
	if backup == None:
		backup = os.path.join(path, "." + basename + ".bak.1")
	if not os.access(backup, os.F_OK):
		return
	shutil.move(backup, target)
	base, num = os.path.splitext(backup)
	bak_num = int(num[1:]) + 1
	next_backup = base + "." + str(bak_num)
	revert_backup (backup, next_backup)

if __name__=='__main__':
	pop_last(*sys.argv[1:])
