#!/usr/bin/env python

import os
import shutil
import stat
import sys

def pop_last (manifest_filename = ".untar-nc_manifest"):
	# Read manifest and revert the changes
	if not os.access(manifest_filename, os.R_OK):
		sys.exit(1)
	try:
		manifest = open(manifest_filename)
		revert_all(manifest)
	finally:
		manifest.close()
	revert_backup(manifest_filename)

def revert_all (manifest):
	manifest_lines = manifest.readlines()
	manifest_lines.reverse()
	for line in manifest_lines:
		if line[-1] == "\n":
			line = line[:-1]
		if line[0] == "/":
			line = line[1:]
			line_parts = line.split(",")
			if len(line_parts) >= 4 and stat.S_ISDIR(os.stat(line_parts[0]).st_mode):
				mode = int(line_parts[-3].split(":")[0])
				uid = int(line_parts[-2].split(":")[0])
				gid = int(line_parts[-1].split(":")[0])
				line = "".join(line_parts[:-3])
				os.chmod(line, mode)
				os.chown(line, uid, gid)
				continue
			else:
				print "Error, corrupt line: " + line
				sys.exit(2)
		revert_backup(line)

def revert_backup (target, backup=None):
	path, basename = os.path.split(target)
	if backup == None:
		backup = os.path.join(path, "." + basename + ".bak.1")
	if not os.access(backup, os.F_OK):
		if stat.S_ISDIR(os.stat(target).st_mode):
			os.rmdir(target)
			return
		else:
			os.remove(target)
			return
	shutil.copy2(backup, target)
	base, num = os.path.splitext(backup)
	bak_num = int(num[1:]) + 1
	next_backup = base + "." + str(bak_num)
	revert_backup (backup, next_backup)

if __name__=='__main__':
	pop_last(*sys.argv[1:])
